"""
Report generator for RAG evaluation results.

Combines retrieval and response evaluation results
into a single Markdown report.
"""

from datetime import datetime
from pathlib import Path

from src.config import (
    DENSE_MODEL,
    RERANK_MODEL,
    RERANK_ENABLED,
    TOP_K_CHILD_CHUNKS,
    RETRIEVAL_CANDIDATES,
    SIMILARITY_THRESHOLD,
    LLM_MODEL,
)


def generate_report(
    retrieval_results: dict,
    response_results: dict,
    output_dir: str = "evaluate/results"
) -> str:
    """
    Generate a Markdown evaluation report.

    Args:
        retrieval_results: Output from run_retrieval_eval()
        response_results: Output from run_response_eval()
        output_dir: Directory to save the report

    Returns:
        Path to the generated report file
    """
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    output_path = Path(output_dir) / f"eval_report_{timestamp}.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    r_agg = retrieval_results["aggregate"]
    resp_agg = response_results["aggregate"]

    lines = [
        f"# RAG Evaluation Report",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Configuration",
        "",
        f"| Parameter | Value |",
        f"|-----------|-------|",
        f"| LLM | {LLM_MODEL} |",
        f"| Embedding | {DENSE_MODEL} |",
        f"| Reranking | {'Enabled (' + RERANK_MODEL + ')' if RERANK_ENABLED else 'Disabled'} |",
        f"| Retrieval Candidates | {RETRIEVAL_CANDIDATES} |",
        f"| Top K (final) | {TOP_K_CHILD_CHUNKS} |",
        f"| Similarity Threshold | {SIMILARITY_THRESHOLD} |",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Metric | Score |",
        "|--------|-------|",
        f"| **Precision@{TOP_K_CHILD_CHUNKS}** | {r_agg['mean_precision_at_k']:.3f} |",
        f"| **MRR** | {r_agg['mrr']:.3f} |",
        f"| **Faithfulness** | {resp_agg['mean_faithfulness']:.2f} / 5 |",
        f"| **Answer Relevance** | {resp_agg['mean_relevance']:.2f} / 5 |",
        f"| Questions Evaluated | {r_agg['total_questions']} |",
        f"| Errors | {resp_agg.get('errors', 0)} |",
        "",
        "---",
        "",
        "## Retrieval Results (per question)",
        "",
        "| ID | Question | P@k | RR | Retrieved Sources |",
        "|----|----------|-----|----|--------------------|",
    ]

    for r in retrieval_results["per_question"]:
        sources = ", ".join(r["retrieved_sources"][:3])
        q_short = r["question"][:50] + "..." if len(r["question"]) > 50 else r["question"]
        lines.append(
            f"| {r['id']} | {q_short} | {r['precision_at_k']:.3f} | {r['reciprocal_rank']:.3f} | {sources} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## Response Results (per question)",
        "",
        "| ID | Question | Faithfulness | Relevance | Notes |",
        "|----|----------|-------------|-----------|-------|",
    ])

    for r in response_results["per_question"]:
        q_short = r["question"][:50] + "..." if len(r["question"]) > 50 else r["question"]
        if "error" in r:
            lines.append(f"| {r['id']} | {q_short} | ERROR | ERROR | {r['error'][:50]} |")
        else:
            reason = r.get("faithfulness_reason", "")[:40]
            lines.append(
                f"| {r['id']} | {q_short} | {r['faithfulness_score']}/5 | {r['relevance_score']}/5 | {reason} |"
            )

    lines.extend(["", "---", f"", f"Generated by Singapore Housing Assistant Evaluation System"])

    report_content = "\n".join(lines)
    output_path.write_text(report_content, encoding="utf-8")

    return str(output_path)
